// app/layout.js

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider"; // 👈 import user provider
import { Toaster } from "sonner";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] })
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>   {/* ✅ wrap everything */}
          {children}
          <Toaster/>
        </Provider>
      </body>
    </html>
  )
}
