// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider"; // ✅ your context provider
import { Toaster } from "sonner";
import { SpeedInsights } from "@vercel/speed-insights/next"; // ✅ import

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>
          {children}
          <Toaster />
          <SpeedInsights /> 
        </Provider>
      </body>
    </html>
  );
}
