name: CI — Lint, Test, Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SUPABASE_URL: "https://mock-project.supabase.co"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "mock-anon-key"
      SUPABASE_SERVICE_ROLE_KEY: "mock-service-role-key"
      OPENROUTER_API_KEY: "mock-openrouter-key"
      GROQ_API_KEY: "mock-groq-key"
      NVIDIA_API_KEY: "mock-nvidia-key"
      NODE_ENV: "test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build Next.js app
        run: npm run build
